apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace_techtalk.yaml
- configmap_nginx_index.yaml
- configmap_nginx.yaml
- service_nginx.yaml
- route_nginx.yaml
- deployment_nginx.yaml
